require 'rubygems'
require 'active_support'
require 'active_support/core_ext/numeric'
require 'action_view'
require 'pathname'
require 'json'
require 'aws-sdk'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  raise "missing ENV['S3_ACCESS_KEY_ID']" unless ENV['S3_ACCESS_KEY_ID']
  raise "missing ENV['S3_SECRET_ACCESS_KEY']" unless ENV['S3_SECRET_ACCESS_KEY']
  AWS::config(
    :access_key_id => ENV['S3_ACCESS_KEY_ID'],
    :secret_access_key => ENV['S3_SECRET_ACCESS_KEY']
  )
  $bucket = ENV['S3_BUCKET']
end

require File.expand_path(File.dirname(__FILE__) + "/../lib/s3lurp")



# some dummy classes
class Rails
  class << self
    attr_accessor :env, :root
  end
  @env = 'development'
  @root = Pathname.new(File.expand_path(File.dirname(__FILE__) + "/support"))
end

class Klass

end

class Parent
  attr_accessor :id
  def self.find(id)
    Parent.new(id)
  end
  def initialize(id)
    @id = id
  end

end
